### ISSUE TITLE
airbase: associate runways with an airbase instance

### ISSUE THREAD

**Issue by jtoppins** [jtoppins/dct#120]
Use a segmented rectangle to track damage over a given area. Once X% of the runway is damaged it is considered non-operational, once all runways for an airbase are not operational the airbase is not operational.

The runtime of the detection of which section of the runway has been damaged should be, O(n) = log2(n), likely each section will have a "strength" value and if a weapon does not meet the strength level, based on warhead size, that section is not damaged. This could produce scenarios where a "dirt" runway could be damaged by rockets, but the runway at Al Dhafra, simulating a reinforced grooved concrete surface, would need at least a Mk-82 dropped on a section to damage it.

## Tasks

- [x] read in the airbase DB
- [x] have the AirbaseAsset setup runway information
- [ ] calculate runway sections subsections
- [ ] marshal only which subsections have been hit, no need to marshal runway subsection geometry as that can be recalculated
- [ ] use a binary search to calculate which section was hit
- [x] use [efficient point in non-axis-aligned rectangle detection](https://math.stackexchange.com/a/190373) to determine which section was hit
- [ ] use [this](https://stackoverflow.com/questions/1560492/how-to-tell-whether-a-point-is-to-the-right-or-left-side-of-a-line) to calculate right or left
