### ISSUE TITLE
weapon tracking and impact notification system

### ISSUE THREAD

**Issue by jtoppins** [jtoppins/dct#121]
## Overview

DCS currently does not provide weapon impact events, shot events exist but no impact events for some reason. In any case for certain features impact events are needed thus this bug intends to track and artificially create weapon impact events and issue them to the common Theater event handler. 

## Design Details

To limit the number of weapons we need to track only track **H**igh **E**xplosive (HE) style warhead weapons.

TODOS:
 * Frequency of polling for tracked weapons
 * how can we detect impacts with things like bridges?

## Tasks

- [x] write handler to catch DCS shot events and track specific kinds of weapons
- [x] track a weapon until it impacts the ground
- [x] upon impacting the ground issue an impact event via the theater event handler
